[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/templates/index.html"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Proxy API calls to your Render backend
[[redirects]]
  from = "/scan"
  to = "https://diallens.onrender.com/scan"
  status = 200
  force = true